// <auto-generated />
using System;
using EduPsych_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduPsych_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510113048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduPsych_Web.Models.Administrator", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("administrator");
                });

            modelBuilder.Entity("EduPsych_Web.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.ChatRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatRoom");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Class", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.CounselSession", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount_paid")
                        .HasColumnType("numeric");

                    b.Property<decimal>("counselor_commission")
                        .HasColumnType("numeric");

                    b.Property<long>("counselor_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("meeting_link")
                        .HasColumnType("text");

                    b.Property<decimal>("platform_commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("scheduled_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("session_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("counselor_id");

                    b.HasIndex("student_id");

                    b.ToTable("counsel_session", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Counselor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("available_days")
                        .HasColumnType("text");

                    b.Property<string>("available_hours")
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<string>("ccp_number")
                        .HasColumnType("text")
                        .HasColumnName("ccp_number");

                    b.Property<decimal?>("hourly_price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("rib_number")
                        .HasColumnType("text")
                        .HasColumnName("rib_number");

                    b.Property<long?>("specialization_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("specialization_id");

                    b.HasIndex("user_id");

                    b.ToTable("counselor", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.CounselorWallet", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("counselor_id")
                        .HasColumnType("bigint")
                        .HasColumnName("counselor_id");

                    b.Property<decimal>("total_earned")
                        .HasColumnType("numeric")
                        .HasColumnName("total_earned");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("withdrawn_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("withdrawn_amount");

                    b.HasKey("id");

                    b.HasIndex("counselor_id");

                    b.ToTable("counselor_wallet");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Course", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("class_id")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_published")
                        .HasColumnType("boolean");

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("promo_video_url")
                        .HasColumnType("text");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<long>("teacher_id")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<decimal>("teacher_percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("teacher_percentage");

                    b.Property<string>("thumbnail_url")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.HasIndex("subject_id");

                    b.HasIndex("teacher_id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.CourseEnrollment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount_paid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_paid");

                    b.Property<long>("course_id")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("enrolled_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<decimal>("platform_commission")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("platform_commission");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<decimal>("teacher_commission")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("teacher_commission");

                    b.HasKey("id");

                    b.HasIndex("course_id");

                    b.HasIndex("student_id");

                    b.ToTable("course_enrollments", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.DepositRequest", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("receipt_image_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("student_id");

                    b.ToTable("deposit_requests", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.EducationalSession", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("lesson_id")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<string>("meeting_link")
                        .HasColumnType("text");

                    b.Property<DateTime>("scheduled_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("session_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("id");

                    b.HasIndex("lesson_id");

                    b.HasIndex("student_id");

                    b.ToTable("educational_session", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Exam", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("exam_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("file_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("subject_id");

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Exercise", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("file_url")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<long>("lesson_id")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("pdf_url")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("lesson_id");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Lesson", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("class_id")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long?>("course_id")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("is_free")
                        .HasColumnType("boolean");

                    b.Property<string>("pdf_summary_url")
                        .HasColumnType("text");

                    b.Property<string>("pdf_url")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<long>("subject_id")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<long>("teacher_id")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("video_url")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.HasIndex("course_id");

                    b.HasIndex("subject_id");

                    b.HasIndex("teacher_id");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Notification", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("counselor_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("student_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("teacher_id")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Parent", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("student_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("student_id");

                    b.HasIndex("user_id");

                    b.ToTable("parent", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Payment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<long?>("counsel_session_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("educational_session_id")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("counsel_session_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.PsychSpecialization", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("psych_specialization");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Review", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<long?>("counsel_session_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("educational_session_id")
                        .HasColumnType("bigint");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("counsel_session_id");

                    b.HasIndex("educational_session_id");

                    b.HasIndex("student_id");

                    b.ToTable("review");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Role", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Stream", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("class_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.ToTable("stream", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Student", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("class_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.HasIndex("user_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.StudentWallet", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("student_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.HasIndex("student_id");

                    b.ToTable("student_wallets", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Subject", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("stream_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("stream_id");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.Teacher", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("available_days")
                        .HasColumnType("text")
                        .HasColumnName("available_days");

                    b.Property<string>("available_hours")
                        .HasColumnType("text")
                        .HasColumnName("available_hours");

                    b.Property<string>("bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("ccp_number")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("hourly_price")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("hourly_price");

                    b.Property<string>("rib_number")
                        .HasColumnType("text");

                    b.Property<long?>("specialization_id")
                        .HasColumnType("bigint")
                        .HasColumnName("specialization_id");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("video_intro_url")
                        .HasColumnType("text")
                        .HasColumnName("video_intro_url");

                    b.Property<int>("years_of_experience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("id");

                    b.HasIndex("specialization_id");

                    b.HasIndex("user_id");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.TeacherWallet", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("pending_clearance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("teacher_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("total_earned")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("withdrawn_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("id");

                    b.HasIndex("teacher_id");

                    b.ToTable("teacher_wallet", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone_number")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("profile_picture_url")
                        .HasColumnType("text");

                    b.Property<long>("role_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EduPsych_Web.Models.WithdrawalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long?>("CounselorId")
                        .HasColumnType("bigint")
                        .HasColumnName("counselor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TransferReceiptUrl")
                        .HasColumnType("text")
                        .HasColumnName("transfer_receipt_url");

                    b.Property<long?>("counselor_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CounselorId");

                    b.HasIndex("TeacherId");

                    b.ToTable("withdrawal_requests", t =>
                        {
                            t.Property("counselor_id")
                                .HasColumnName("counselor_id1");
                        });
                });

            modelBuilder.Entity("EduPsych_Web.Models.specialization", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("specialization");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Administrator", b =>
                {
                    b.HasOne("EduPsych_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPsych_Web.Models.ChatMessage", b =>
                {
                    b.HasOne("EduPsych_Web.Models.ChatRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("EduPsych_Web.Models.CounselSession", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("counselor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Counselor", b =>
                {
                    b.HasOne("EduPsych_Web.Models.PsychSpecialization", "PsychSpecialization")
                        .WithMany()
                        .HasForeignKey("specialization_id");

                    b.HasOne("EduPsych_Web.Models.specialization", "specialization")
                        .WithMany()
                        .HasForeignKey("specialization_id");

                    b.HasOne("EduPsych_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PsychSpecialization");

                    b.Navigation("User");

                    b.Navigation("specialization");
                });

            modelBuilder.Entity("EduPsych_Web.Models.CounselorWallet", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("counselor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counselor");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Course", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("class_id");

                    b.HasOne("EduPsych_Web.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduPsych_Web.Models.CourseEnrollment", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.DepositRequest", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.EducationalSession", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Exam", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Exercise", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Lesson", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("course_id");

                    b.HasOne("EduPsych_Web.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("subject_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Parent", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id");

                    b.HasOne("EduPsych_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Payment", b =>
                {
                    b.HasOne("EduPsych_Web.Models.CounselSession", "CounselSession")
                        .WithMany()
                        .HasForeignKey("counsel_session_id");

                    b.Navigation("CounselSession");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Review", b =>
                {
                    b.HasOne("EduPsych_Web.Models.CounselSession", "CounselSession")
                        .WithMany()
                        .HasForeignKey("counsel_session_id");

                    b.HasOne("EduPsych_Web.Models.EducationalSession", "EducationalSession")
                        .WithMany()
                        .HasForeignKey("educational_session_id");

                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CounselSession");

                    b.Navigation("EducationalSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Stream", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Class", "Class")
                        .WithMany("Streams")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Student", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPsych_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPsych_Web.Models.StudentWallet", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Subject", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Stream", "Stream")
                        .WithMany()
                        .HasForeignKey("stream_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Teacher", b =>
                {
                    b.HasOne("EduPsych_Web.Models.specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("specialization_id");

                    b.HasOne("EduPsych_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPsych_Web.Models.TeacherWallet", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduPsych_Web.Models.User", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduPsych_Web.Models.WithdrawalRequest", b =>
                {
                    b.HasOne("EduPsych_Web.Models.Counselor", "Counselor")
                        .WithMany()
                        .HasForeignKey("CounselorId");

                    b.HasOne("EduPsych_Web.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Counselor");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduPsych_Web.Models.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Class", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Lesson", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("EduPsych_Web.Models.Teacher", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
